#https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

#banner
#  image
#    location=classpath:banner.gif # Banner image file location (jpg/png can also be used).
#    width= # Width of the banner image in chars (default 76)
#    height= # Height of the banner image in chars (default based on image height)
#    margin= # Left hand image margin in chars (default 2)
#    invert= # If images should be inverted for dark terminal themes (default false)


#spring:
#  datasource:
#    url: jdbc:mysql://db4free.net:3307/jbt_db
#    password: Password
#    username: jbt_admin


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jbt_db
    password: Password
    username: root

# FLYWAY (FlywayProperties)
flyway:
  enabled: true
  locations: classpath:db/migration
